import { createFileRoute, useNavigate, Link } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { useAuth, hasActiveAccess, daysLeft } from "@/lib/auth-context";
import { COMPANIES } from "@/lib/companies";
import { generateDocument } from "@/lib/generate-doc.functions";
import jsPDF from "jspdf";

export const Route = createFileRoute("/dashboard")({
  head: () => ({ meta: [{ title: "Dashboard — NexDocs" }] }),
  component: Dashboard,
});

function Dashboard() {
  const { user, profile, loading } = useAuth();
  const navigate = useNavigate();
  const generate = useServerFn(generateDocument);

  const [companyId, setCompanyId] = useState<string | null>(null);
  const [docType, setDocType] = useState<string | null>(null);
  const [fieldsText, setFieldsText] = useState("");
  const [output, setOutput] = useState<string>("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!loading && !user) navigate({ to: "/auth" });
  }, [loading, user, navigate]);

  const company = useMemo(() => COMPANIES.find((c) => c.id === companyId) ?? null, [companyId]);
  const active = hasActiveAccess(profile);
  const dl = daysLeft(profile);

  if (loading || !user) {
    return <div className="mx-auto max-w-2xl px-4 py-20 text-center text-muted-foreground">Loading…</div>;
  }

  const onGenerate = async () => {
    if (!company || !docType) return;
    if (!active) { navigate({ to: "/subscribe" }); return; }
    setBusy(true);
    setError(null);
    setOutput("");
    try {
      const fields: Record<string, string> = {};
      fieldsText.split("\n").forEach((line) => {
        const idx = line.indexOf(":");
        if (idx > 0) {
          const k = line.slice(0, idx).trim();
          const v = line.slice(idx + 1).trim();
          if (k) fields[k] = v;
        }
      });
      const res = await generate({ data: { company: company.name, documentType: docType, fields } });
      if (!res.ok) setError(res.error);
      else setOutput(res.content);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Generation failed");
    } finally {
      setBusy(false);
    }
  };

  const downloadPdf = () => {
    if (!output || !company || !docType) return;
    const pdf = new jsPDF({ unit: "pt", format: "a4" });
    const margin = 48;
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(18);
    pdf.text(docType, margin, margin);
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(10);
    pdf.setTextColor(120);
    pdf.text(`${company.name} • Generated by NexDocs`, margin, margin + 16);
    pdf.setTextColor(0);
    pdf.setFontSize(11);
    const text = output.replace(/[#*_`>]+/g, "");
    const lines = pdf.splitTextToSize(text, pageWidth - margin * 2);
    let y = margin + 40;
    for (const line of lines) {
      if (y > pageHeight - margin) { pdf.addPage(); y = margin; }
      pdf.text(line, margin, y);
      y += 14;
    }
    pdf.save(`${docType.replace(/\s+/g, "_")}.pdf`);
  };

  return (
    <div className="mx-auto max-w-5xl px-4 py-6 sm:py-10">
      <div className="rounded-xl border border-border/60 bg-card/70 p-4 sm:p-5 mb-6 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div>
          <div className="font-display text-xl text-foreground">Welcome{profile?.displayName ? `, ${profile.displayName.split(" ")[0]}` : ""}.</div>
          <div className="text-sm text-muted-foreground">{profile?.email}</div>
        </div>
        <div className="text-sm">
          {profile?.subscriptionStatus === "active" ? (
            <span className="rounded-full bg-gold-gradient px-3 py-1 font-semibold text-primary-foreground">Active subscriber</span>
          ) : active ? (
            <span className="rounded-full border border-gold/60 px-3 py-1 text-gold">Trial • {dl} day{dl === 1 ? "" : "s"} left</span>
          ) : (
            <Link to="/subscribe" className="rounded-full bg-gold-gradient px-3 py-1 font-semibold text-primary-foreground">Subscribe — R99/mo</Link>
          )}
        </div>
      </div>

      <div className="mb-6 grid grid-cols-1 sm:grid-cols-2 gap-3">
        <Link
          to="/leads"
          className="rounded-xl border border-gold/40 bg-card/70 p-4 hover:border-gold transition flex items-center justify-between"
        >
          <div>
            <div className="font-display text-lg text-foreground">Gauteng Lead Finder</div>
            <div className="text-xs text-muted-foreground">Find business leads across Gauteng — live Google data.</div>
          </div>
          <span className="text-gold">→</span>
        </Link>
      </div>

      <h2 className="font-display text-2xl text-foreground mb-3">Choose a company</h2>
      <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
        {COMPANIES.map((c) => (
          <button
            key={c.id}
            onClick={() => { setCompanyId(c.id); setDocType(null); setOutput(""); }}
            className={`text-left rounded-xl border p-3 transition ${companyId === c.id ? "border-gold bg-card" : "border-border/60 bg-card/60 hover:border-gold/60"}`}
          >
            <div className="flex items-center gap-2">
              {c.logo ? (
                <img src={c.logo} alt="" className="h-10 w-10 rounded-md object-cover" />
              ) : (
                <div className="h-10 w-10 rounded-md bg-gold-gradient flex items-center justify-center text-primary-foreground font-display">SA</div>
              )}
              <div>
                <div className="text-sm font-semibold text-foreground leading-tight">{c.name}</div>
                <div className="text-[11px] text-muted-foreground">{c.documents.length} docs</div>
              </div>
            </div>
          </button>
        ))}
      </div>

      {company && (
        <div className="mt-8 rounded-xl border border-border/60 bg-card/70 p-4 sm:p-5">
          <h3 className="font-display text-xl text-foreground mb-3">{company.name} — pick a document</h3>
          <div className="flex flex-wrap gap-2">
            {company.documents.map((d) => (
              <button
                key={d}
                onClick={() => setDocType(d)}
                className={`rounded-full border px-3 py-1.5 text-sm transition ${docType === d ? "border-gold bg-gold-gradient text-primary-foreground font-semibold" : "border-border/60 text-foreground/80 hover:border-gold/60"}`}
              >
                {d}
              </button>
            ))}
          </div>

          {docType && (
            <div className="mt-5">
              <label className="block text-sm font-medium text-foreground mb-2">
                Document details
                <span className="ml-1 text-xs text-muted-foreground">(one per line — e.g. <code>Client name: Acme Pty Ltd</code>)</span>
              </label>
              <textarea
                value={fieldsText}
                onChange={(e) => setFieldsText(e.target.value)}
                placeholder={"Client name: Acme Pty Ltd\nProject: Office renovation\nAmount: R 25 000\nDate: 25 June 2026"}
                rows={6}
                className="w-full rounded-md bg-input border border-border px-4 py-3 text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-gold font-mono text-sm"
              />
              <div className="mt-3 flex flex-col sm:flex-row gap-2">
                <button
                  onClick={onGenerate}
                  disabled={busy}
                  className="rounded-md bg-gold-gradient px-5 py-2.5 font-semibold text-primary-foreground disabled:opacity-60"
                >
                  {busy ? "Generating…" : `Generate ${docType}`}
                </button>
                {output && (
                  <button onClick={downloadPdf} className="rounded-md border border-gold/60 px-5 py-2.5 font-semibold text-foreground">
                    Download PDF
                  </button>
                )}
              </div>
              {error && <div className="mt-3 text-sm text-destructive">{error}</div>}
              {output && (
                <pre className="mt-5 whitespace-pre-wrap rounded-md border border-border/60 bg-background p-4 text-sm text-foreground/90 font-sans">
                  {output}
                </pre>
              )}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
