import { createFileRoute, Link } from "@tanstack/react-router";
import { CNH_LOGO } from "@/lib/firebase";
import { COMPANIES } from "@/lib/companies";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "NexDocs — AI Business Documents for South Africa" },
      { name: "description", content: "Generate professional South African business documents in seconds with AI. 10-day free trial, then R99/month." },
      { property: "og:title", content: "NexDocs — AI Business Documents" },
      { property: "og:description", content: "Contracts, quotes, HR letters, legal forms — generated by AI for SA businesses." },
    ],
  }),
  component: Landing,
});

function Landing() {
  return (
    <div className="mx-auto max-w-6xl px-4">
      <section className="py-14 sm:py-24 text-center">
        <img src={CNH_LOGO} alt="Cossa Nexus Holdings" className="mx-auto h-24 w-24 rounded-2xl object-cover shadow-2xl shadow-black/40" />
        <h1 className="mt-8 font-display text-4xl sm:text-6xl leading-tight">
          <span className="text-gold-gradient">AI Business Documents</span>
          <br />
          <span className="text-foreground">for South Africa</span>
        </h1>
        <p className="mx-auto mt-5 max-w-xl text-base sm:text-lg text-muted-foreground">
          Contracts, quotes, HR letters, legal forms — generated in seconds.
          Built for the Cossa Nexus group and every SA business.
        </p>
        <div className="mt-8 flex flex-col sm:flex-row gap-3 justify-center">
          <Link to="/auth" className="rounded-lg bg-gold-gradient px-6 py-3 font-semibold text-primary-foreground shadow-lg">
            Start 10-day free trial
          </Link>
          <Link to="/auth" className="rounded-lg border border-gold/40 px-6 py-3 font-semibold text-foreground">
            Sign in
          </Link>
        </div>
        <p className="mt-4 text-xs text-muted-foreground">Then just R99/month. Cancel anytime.</p>
      </section>

      <section className="pb-20">
        <h2 className="font-display text-2xl sm:text-3xl text-center text-foreground mb-8">
          Six companies. <span className="text-gold-gradient">Forty-eight documents.</span>
        </h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {COMPANIES.map((c) => (
            <div key={c.id} className="rounded-xl border border-border/60 bg-card/60 p-5 backdrop-blur">
              <div className="flex items-center gap-3">
                {c.logo ? (
                  <img src={c.logo} alt="" className="h-12 w-12 rounded-md object-cover" />
                ) : (
                  <div className="h-12 w-12 rounded-md bg-gold-gradient flex items-center justify-center font-display text-xl text-primary-foreground">SA</div>
                )}
                <div>
                  <div className="font-display text-lg text-foreground">{c.name}</div>
                  <div className="text-xs text-muted-foreground">{c.tagline}</div>
                </div>
              </div>
              <div className="mt-3 text-sm text-gold">{c.documents.length} documents</div>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
