/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicPayfastItnRouteImport } from './routes/api.public.payfast-itn'

const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPayfastItnRoute = ApiPublicPayfastItnRouteImport.update({
  id: '/api/public/payfast-itn',
  path: '/api/public/payfast-itn',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/leads': typeof LeadsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscribe': typeof SubscribeRoute
  '/api/public/payfast-itn': typeof ApiPublicPayfastItnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/leads': typeof LeadsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscribe': typeof SubscribeRoute
  '/api/public/payfast-itn': typeof ApiPublicPayfastItnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/leads': typeof LeadsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscribe': typeof SubscribeRoute
  '/api/public/payfast-itn': typeof ApiPublicPayfastItnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assistant'
    | '/auth'
    | '/dashboard'
    | '/leads'
    | '/sitemap.xml'
    | '/subscribe'
    | '/api/public/payfast-itn'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/assistant'
    | '/auth'
    | '/dashboard'
    | '/leads'
    | '/sitemap.xml'
    | '/subscribe'
    | '/api/public/payfast-itn'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assistant'
    | '/auth'
    | '/dashboard'
    | '/leads'
    | '/sitemap.xml'
    | '/subscribe'
    | '/api/public/payfast-itn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  LeadsRoute: typeof LeadsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubscribeRoute: typeof SubscribeRoute
  ApiPublicPayfastItnRoute: typeof ApiPublicPayfastItnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payfast-itn': {
      id: '/api/public/payfast-itn'
      path: '/api/public/payfast-itn'
      fullPath: '/api/public/payfast-itn'
      preLoaderRoute: typeof ApiPublicPayfastItnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  LeadsRoute: LeadsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubscribeRoute: SubscribeRoute,
  ApiPublicPayfastItnRoute: ApiPublicPayfastItnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
